spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boondb?leuseUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    password: password
    username: boondb_admin
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    user: boondb_admin
    password: password
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
  application:
    name: BoonApp

server:
  port: 5000